name: linting, testing, building

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.11.0]

    steps:
      - uses: actions/checkout@v4

      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Linting TypeScript
        run: yarn lint:ts

      - name: Linting CSS
        run: yarn lint:scss

      - name: Unit testing
        run: yarn test:unit

      - name: Build Storybook
        run: yarn build:sb

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps chromium

      - name: Screenshot testing
        run: yarn test:ui:ci

      - name: Build production project
        run: yarn build:prod
